Repository openshift-knative/net-kourier, pull requests merged in 2025-04, with the labels that each got.

#288 Allow to disable envoy server header injection (#1311)
  .golangci.yaml
  config/200-config.yaml
  pkg/config/configmap.go
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
Labels: approved, lgtm

#277 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/components/net-kourier-kourier-116.yaml
  .tekton/docker-build.yaml
  .tekton/net-kourier-kourier-116-pull-request.yaml
  .tekton/net-kourier-kourier-116-push.yaml
Labels: lgtm, ok-to-test

#293 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved

#292 [release-v1.16] Update Konflux configurations
  .tekton/net-kourier-kourier-116-pull-request.yaml
  .tekton/net-kourier-kourier-116-push.yaml
Labels: lgtm

#278 [release-v1.17] Update Konflux configurations
  .tekton/docker-build.yaml
  .tekton/net-kourier-kourier-117-pull-request.yaml
  .tekton/net-kourier-kourier-117-push.yaml
Labels: needs-ok-to-test
