Repository openshift-knative/net-kourier, pull requests merged in 2025-05, with the labels that each got.

#301 [main] Update dependabot configurations
  renovate.json
Labels: lgtm

#306 [release-v1.17] Fix version string in yaml
  openshift/release/artifacts/net-kourier.yaml
Labels: approved, lgtm

#308 Update OWNERS
  OWNERS
Labels: approved
